### ISSUE TITLE
Overriding your libraries

### ISSUE THREAD

**Issue by jellydonuts** [xenomedia/xeno_hero#19]
Great module, however I'm finding it very difficult to override your js library in my custom bootstrap subtheme.

I need to override your js file and have tried all the possible combinations to override however I feel like I'm missing the proper library naming scheme. Any ideas how I would go about doing this in my theme.info.yml's libraries-override section?

I even found a few bugs regarding overriding already overridden libraries requiring the absolute path relative to the root but still have no luck in preventing your js from attaching:
```

libraries-override:
  xenomedia/xeno-hero:
    js:
      js/xeno-hero.js: false
      /modules/custom/xeno_hero/js/xeno-hero.js: false
  mytheme/xeno-hero:
    js:
      js/xeno-hero.js: false
      /modules/custom/xeno_hero/js/xeno-hero.js: false
  xeno-hero/xeno-hero:
    js:
      js/xeno-hero.js: false
      /modules/custom/xeno_hero/js/xeno-hero.js: false
  xeno-hero:
    js:
      js/xeno-hero.js: false
      /modules/custom/xeno_hero/js/xeno-hero.js: false

```

**Comment by jellydonuts** [comment]
oh my god, i feel like a dumbass!

I've been wracking my brain for the last 3 hours... you're using an underscore in the filename, but a dash in the library name!

```
libraries-override:
  xeno_hero/xeno-hero:
    js:
      js/xeno-hero.js: js/xeno-hero-override.js

```
